config/routes.rb
Rails.application.routes.draw do
  # resources :portfolio, only: [:index] do
  #   collection do
  #     get :show
  #   end
  # end
  get "portfolio/index"
  get "portfolio/show"

  mount RailsAdmin::Engine => "/admin", as: "rails_admin"
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
  root "portfolio#index"
end

app/models/ability.rb
# frozen_string_literal: true

class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the user here. For example:
    #
    #   return unless user.present?
    #   can :read, :all
    #   return unless user.admin?
    #   can :manage, :all
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, published: true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/blob/develop/docs/define_check_abilities.md

    return unless user.present?

    can :access, :rails_admin
    can :read, :dashboard
    can :read, User, id: user.id
    can :manage, Profile, user: user
    can :manage, Project, user: user
    can :read, Phase
    can :read, Position
    can :read, TechCategory
    can :read, TechTag

    return unless user.admin?
    can :manage, :all
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/phase.rb
class Phase < ApplicationRecord
  has_and_belongs_to_many :projects, join_table: :projects_phases

  validates :name, presence: true, length: { maximum: 255 }
  validates :display_order, presence: true, numericality: { only_integer: true }
end

app/models/position.rb
class Position < ApplicationRecord
  has_and_belongs_to_many :projects, join_table: :projects_positions

  validates :name, presence: true, length: { maximum: 255 }
  validates :display_order, presence: true, numericality: { only_integer: true }
end

app/models/profile.rb
class Profile < ApplicationRecord
  belongs_to :user

  scope :published, -> { where(published: true) }
end

app/models/project.rb
class Project < ApplicationRecord
  belongs_to :user
  has_one_attached :hw_diagram
  has_one_attached :sw_diagram
  has_and_belongs_to_many :tech_tags
  has_and_belongs_to_many :phases, join_table: :projects_phases
  has_and_belongs_to_many :positions, join_table: :projects_positions

  scope :published, -> { where(published: true) }

  # for deletion
  attr_accessor :remove_hw_diagram
  after_save { hw_diagram.purge if remove_hw_diagram == "1" }
  attr_accessor :remove_sw_diagram
  after_save { sw_diagram.purge if remove_sw_diagram == "1" }
end

app/models/tech_category.rb
class TechCategory < ApplicationRecord
  belongs_to :parent, class_name: "TechCategory", inverse_of: :children, optional: true

  has_many :children, -> { order(:display_order) }, class_name: "TechCategory", foreign_key: :parent_id, inverse_of: :parent
  has_many :tech_tags, -> { order(:display_order) }, inverse_of: :tech_category

  scope :top_levels, -> { where(parent_id: nil) }
end

app/models/tech_tag.rb
class TechTag < ApplicationRecord
  belongs_to :tech_category
  has_and_belongs_to_many :projects

  validates :name, presence: true, length: { maximum: 255 }
  validates :display_order, presence: true, numericality: { only_integer: true }

  class << self
    def project_ids(ids)
      self.where(id: ids).map { |tag| tag.projects.pluck(:id) }.flatten.uniq if ids.present?
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  # devise :database_authenticatable, :registerable,
  #        :recoverable, :rememberable, :validatable
  devise :database_authenticatable, :recoverable, :validatable

  enum :role, {
    administrator: 1,
    owner: 2
  }

  has_one :profile

  scope :published, -> { joins(:profile).merge(Profile.published) }

  def self.find_for_database_authentication(warden_conditions)
    find_by(email: warden_conditions[:email], available: true)
  end

  def admin?
    self.administrator?
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  add_flash_types :warning
end

app/controllers/portfolio_controller.rb
class PortfolioController < ApplicationController
  before_action :init_conditions

  def index
    @portfolio_form = PortfolioForm.new

    flash.now[:warning] = "リソースが非常に貧弱な環境で動作しています。\n負荷低減にご協力ください。"
  end

  def show
    form = params.require(:portfolio_form).permit(:user_id, { tech_tag_ids: {} }, :count)
    @portfolio_form = PortfolioForm.new(form)

    @target_user = User.published.find_by(id: params[:portfolio_form][:user_id]) if @portfolio_form.valid?

    @projects = ProjectDecorator.decorate_collection(@portfolio_form.search)

    render :index
  end

  private

  def init_conditions
    @tech_categories = TechCategory.includes(:tech_tags).top_levels.order(:display_order)
    @users = UserDecorator.decorate_collection(User.published)
    @counts = [ [ 5, 5 ], [ 10, 10 ], [ 30, 30 ], [ "全て", -1 ] ]
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def nl2br(str)
    raw(h(str).gsub("\n", tag.br))
  end

  def alert_type(message_type)
    type = ""
    type = "info" if message_type == "notice"
    type = "warning" if message_type == "warning"
    type = "danger"  if message_type == "alert"
    type
  end
end

app/helpers/portfolio_helper.rb
module PortfolioHelper
  # 文字列を数値文字参照に変換する。
  def numerical_character_references(str)
    if str.nil?
      return ""
    end

    str.bytes.map { |v| "&\#x#{v.to_s(16)};" }.join
  end

  # Unicode数値参照で偽装したmailtoリンクを生成する。
  def mailto_link(user)
    if user.nil?
      return ""
    end

    mailto = numerical_character_references("mailto:")
    converted = numerical_character_references(user.email)
    tag.a converted, href: "#{mailto}#{converted}", escape: false
  end
end

app/views/layouts/_footer.html.erb
&copy; KONISHI Toru

app/views/layouts/_header.html.erb
<%= link_to t(:application_name), root_url, id: "logo", class: "navbar-brand" %>

<div class="header-space"></div>

<nav>
  <% if user_signed_in? %>
    <%= link_to t(:admin_name), rails_admin.dashboard_path %>
    <%= link_to t(:sign_out), destroy_user_session_path, data: { turbo_method: :delete } %>
  <% else %>
    <%= link_to t(:sign_in), new_user_session_path %>
  <% end %>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ポートフォリオ</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body class="portfolio">
    <header class="header">
      <%= render 'layouts/header' %>
    </header>

    <main>
      <%= yield %>
    </main>

    <footer>
      <%= render 'layouts/footer' %>
    </footer>
  </body>
</html>

app/views/portfolio/_portfolio.html.erb
<% if @target_user.present? %>
  <hr>
  <style>
    h2 {
      margin-top: 1rem;
    }

    h4 a.btn {
      border: 0px;
      padding: 0px;
      font-size: 1.25rem;
      font-weight: 500;
      line-height: 1.2;
    }
  </style>
  <div class="container px-0 pt-2">
    <h2>自己紹介</h2>
    <%= simple_format(h(@target_user.profile.introduction)) %>

    <% if @projects.present? %>
    <h2>主な開発実績</h2>
    <div class="projects" id="projlist">
      <% @projects.each.with_index(1) do |project, idx| %>
        <details>
          <summary><%= project.title %></summary>
          <div>
            <% if project.overview.present? %>
              <h5>概要</h5>
              <%= simple_format(h(project.overview)) %>
            <% end %>
            <% if project.has_hw_configuration? %>
              <h5>HW構成</h5>
              <%= simple_format(h(project.hw_configuration)) %>
              <% if project.hw_diagram.attached? %>
                <figure>
                  <%= image_tag project.hw_diagram %>
                  <figcaption>HW構成図</figcaption>
                </figure>
              <% end %>
            <% end %>
            <% if project.has_sw_configuration? %>
              <h5>SW構成</h5>
              <%= simple_format(h(project.sw_configuration)) %>
              <% if project.sw_diagram.attached? %>
                <figure>
                  <%= image_tag project.sw_diagram %>
                  <figcaption>SW構成図</figcaption>
                </figure>
              <% end %>
            <% end %>
            <% if project.job_description.present? %>
              <h5><%= t('activerecord.attributes.project.job_description') %></h5>
              <%= simple_format(h(project.job_description)) %>
            <% end %>
            <% if project.tech_tags.present? %>
              <h5>使用技術</h5>
              <p>
                <%= project.tech_tags_text %>
              </p>
            <% end %>
            <% if project.phases.present? %>
              <h5>担当フェーズ</h5>
              <p>
                <%= project.phases_text %>
              </p>
            <% end %>
            <% if project.positions.present? %>
              <h5>役割</h5>
              <p>
                <%= project.positions_text %>
              </p>
            <% end %>
            <% if project.production_url.present? %>
              <h5>本番環境URL</h5>
              <p><%= link_to project.production_url, project.production_url, target: :_blank %></p>
            <% end %>
            <% if project.repository_url.present? %>
              <h5>リポジトリURL</h5>
              <p><%= link_to project.repository_url, project.repository_url, target: :_blank %></p>
            <% end %>
            <% if project.from.present? || project.to.present? %>
              <h5>期間</h5>
              <p><%= project.project_period %></p>
            <% end %>
          </div>
        </details>
      <% end %>
    </div>
    <% end %>

    <h2>連絡先</h2>
    <p><%= mailto_link @target_user %></p>
  </div>
<% end %>

app/views/portfolio/index.html.erb
<% flash.each do |message_type, message| %>
  <div class="notice alert alert-<%= alert_type(message_type) %>" role="alert">
    <%= nl2br(message) %>
  </div>
<% end %>
<h1>ポートフォリオ</h1>

<%= form_with model: @portfolio_form, url: portfolio_show_path, method: :get, local: true, html:  {} do |f| %>
  <div class="form-group row">
    <%= f.label :user_id, 'ユーザ:', class: "col-sm-2 control-label" %>
    <div class="col-sm-6">
      <%= f.collection_select :user_id,
      @users, :id, :name,
      {},
      {class: "custom-select"} %>
    </div>
  </div>

  <div class="no-print">
    <details>
      <summary>詳細条件</summary>
      <div>
        <fieldset>
          <legend>技術要素</legend>
          <% @tech_categories.each do |category| %>
          <div class="category-condition">
            <label class="category"><%= category.name %>:</label>
            <div class="tech-tags">
              <%= f.collection_check_boxes :tech_tag_ids, category.tech_tags, :id, :name, {include_hidden: false, checked: @portfolio_form.tech_tag_ids[category.id.to_s]}, {name: "portfolio_form[tech_tag_ids][#{category.id}][]"} do |b| %>
                <div>
                  <%= b.label { b.check_box + b.text } %>
                </div>
              <% end %>
            </div>
          </div>
        <% end %>
    </fieldset>
      </div>
    </details>
  </div>

  <div class="form-group row col-sm-2 control-label no-print">
    <div class="col-sm-2">
      <%= f.select :count,
      @counts,
      {},
      {class: "custom-select"} %>
    </div>
  </div>

  <div class="form-group row no-print">
    <div class="col-sm-offset-2 col-sm-10">
      <%= f.submit '表示', class: "btn btn-primary" %>
    </div>
  </div>

<% end %>

<%= render 'portfolio' %>